src/Entity/Evenement.php
<?php

namespace App\Entity;

use App\Repository\EvenementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EvenementRepository::class)]
class Evenement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30)]
    private ?string $responsable_email = null;

    #[ORM\Column]
    private ?int $responsable_id = null;

    #[ORM\Column(length: 100)]
    private ?string $titreevets = null;

    #[ORM\Column(type: "text", nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: "date")]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: "date", nullable: true)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column(length: 50)]
    private ?string $lieu = null;

    #[ORM\Column(type: "integer", nullable: true)]
    private ?int $nombre_participants_max = null;

    #[ORM\Column(type: "boolean", options: ["default" => false])]
    private bool $valider = false;

    #[ORM\Column(type: "boolean", options: ["default" => false])]
    private bool $refuser = false;

    #[ORM\Column(length: 50)]
    private ?string $type_events = null;

    #[ORM\OneToMany(mappedBy: "evenement", targetEntity: Reservation::class, cascade: ["persist", "remove"])]
    private Collection $reservations;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: "evenements")]
    #[ORM\JoinColumn(nullable: true)]
    private ?User $user = null;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getResponsableEmail(): ?string
    {
        return $this->responsable_email;
    }

    public function setResponsableEmail(?string $responsable_email): void
    {
        $this->responsable_email = $responsable_email;
    }

    public function getResponsableId(): ?int
    {
        return $this->responsable_id;
    }

    public function setResponsableId(int $responsable_id): static
    {
        $this->responsable_id = $responsable_id;
        return $this;
    }

    public function getTitreevets(): ?string
    {
        return $this->titreevets;
    }

    public function setTitreevets(string $titreevets): static
    {
        $this->titreevets = $titreevets;
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;
        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;
        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;
        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): static
    {
        $this->lieu = $lieu;
        return $this;
    }

    public function getNombreParticipantsMax(): ?int
    {
        return $this->nombre_participants_max;
    }

    public function setNombreParticipantsMax(?int $nombre_participants_max): static
    {
        $this->nombre_participants_max = $nombre_participants_max;
        return $this;
    }

    public function getValider(): bool
    {
        return $this->valider;
    }

    public function setValider(bool $valider): static
    {
        $this->valider = $valider;
        return $this;
    }

    public function getTypeEvents(): ?string
    {
        return $this->type_events;
    }

    public function setTypeEvents(string $type_events): static
    {
        $this->type_events = $type_events;
        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): static
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations->add($reservation);
            $reservation->setEvenement($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): static
    {
        if ($this->reservations->removeElement($reservation)) {
            if ($reservation->getEvenement() === $this) {
                $reservation->setEvenement(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;
        return $this;
    }

    public function isRefuser(): bool
    {
        return $this->refuser;
    }

    public function setRefuser(bool $refuser): void
    {
        $this->refuser = $refuser;
    }
}

templates/page/Events/Events_details.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <section class="heading-page header-text" id="top">
        <div class="container">
            <div class="row ">
                <div class="col-lg-12">
                    <h2>{{ event.titreevets }}</h2>
                </div>
            </div>
        </div>
    </section>

    <section class="meetings-page" id="meetings">
        <div class="container">
            <div class="row justify-content-center ">
                <div class="col-7 ">
                    <div class="meeting-single-item">
                        <div class="thumb">
                            <div class="price">
                                <span>{{ event.typeEvents|default('General Event') }}</span>
                            </div>
                            <div class="date">
                                <h6>{{ event.dateDebut|date('M') }} <span>{{ event.dateDebut|date('d') }}</span></h6>
                            </div>
                            <img src="{{ asset('images/' ~ (event.image|default('meeting-02.jpg'))) }}" alt="Event Image">
                        </div>
                        <div class="down-content">
                            <h4>{{ event.titreevets }}</h4>
                            <p><strong>Location:</strong> {{ event.lieu }}</p>
                            <p class="description">
                                {{ event.description }}
                            </p>
                            <div class="row">
                                <div class="col-lg-4 col-md-6">
                                    <div class="hours">
                                        <h5>Start Date</h5>
                                        <p>{{ event.dateDebut|date('Y-m-d') }}</p>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-6">
                                    <div class="hours">
                                        <h5>End Date</h5>
                                        <p>{{ event.dateFin|date('Y-m-d') }}</p>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-12">
                                    <div class="main-button-red">
                                        <a href="{{ path('app_page_event') }}">Book now</a>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="share">
                                        <h5>Share:</h5>
                                        <ul>
                                            <li><a href="#">Facebook</a></li>
                                            <li><a href="#">Twitter</a></li>
                                            <li><a href="#">LinkedIn</a></li>
                                            <li><a href="#">Behance</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="main-button-red">
                        <a href="{{ path('app_page_event') }}">Back To Events List</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer">
            <p>&copy; 2024 Esprit.com, Ltd. All Rights Reserved.</p>
        </div>
    </section>
{% endblock %}

templates/page/Events/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}


    <section class="heading-page header-text" id="top">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h6>Here are our upcoming events</h6>
                    <h2>Upcoming Events</h2>
                </div>
            </div>
        </div>
    </section>

    <section class="meetings-page" id="meetings">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="filters d-flex justify-content-between align-items-center">
                                <ul class="d-inline-flex">
                                    <li data-filter="*" class="active">All Events</li>
                                    <li data-filter=".soon">Soon</li>
                                    <li data-filter=".imp">Important</li>
                                    <li data-filter=".att">Attractive</li>
                                </ul>
                                <!-- Button -->
                                <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createEventModal">
                                    Create Event
                                </button>
                            </div>
                        </div>
                    </div>

                    <!-- Event Items -->
                    <div class="row grid">
                        {% for event in events %}
                            {% if event.valider %}
                                <div class="col-lg-4 templatemo-item-col all">
                                    <div class="meeting-item">
                                        <div class="thumb">
                                            <div class="price"><span>{{ event.typeEvents }}</span></div>
                                            <a href="{{ path('app_event_details', {id: event.id}) }}">
                                                <img src="{{ asset('images/' ~ (event.image|default('meeting-02.jpg'))) }}" alt="">
                                            </a>
                                        </div>
                                        <div class="down-content">
                                            <div class="date">
                                                <h6>{{ event.dateDebut|date('M') }} <span>{{ event.dateDebut|date('d') }}</span></h6>
                                            </div>                                            <a href="{{ path('app_event_details', {id: event.id}) }}">
                                                <h4>{{ event.titreevets }}</h4>
                                            </a>
                                            <p class="description">{{ event.description }}</p>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="modal fade" id="createEventModal" tabindex="-1" aria-labelledby="createEventModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content shadow-lg rounded">
                <div class="modal-header bg-primary text-white">
                    <h5 class="modal-title" id="createEventModalLabel">Create a New Event</h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <p class="text-muted mb-3">Fill in the form below to create a new event. Fields marked with <span class="text-danger">*</span> are required.</p>
                    {{ form_start(eventForm, { 'attr': {'class': 'needs-validation'} }) }}
                    <div class="row g-3">
                        <div class="col-md-6">
                            {{ form_row(eventForm.titreevets, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="col-md-6">
                            {{ form_row(eventForm.type_events, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="col-md-6">
                            {{ form_row(eventForm.date_debut, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="col-md-6">
                            {{ form_row(eventForm.date_fin, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="col-12">
                            {{ form_row(eventForm.description, {'attr': {'class': 'form-control', 'rows': '4'}}) }}
                        </div>
                        <div class="col-md-6">
                            {{ form_row(eventForm.lieu, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="col-md-6">
                            {{ form_row(eventForm.nombre_participants_max, {'attr': {'class': 'form-control'}}) }}
                        </div>
                    </div>
                    <div class="mt-4 text-end">
                        <button type="submit" class="btn btn-success px-4">Create Event</button>
                        <button type="button" class="btn btn-secondary px-4" data-bs-dismiss="modal">Cancel</button>
                    </div>
                    {{ form_end(eventForm) }}
                </div>
            </div>
        </div>
    </div>



    <style>
        .footer {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 20px;
            color: #333;
        }

        .footer p {
            margin: 0;
        }

        .right-icons ul {
            display: flex;
            list-style: none;
            padding: 0;
            margin: 0;
        }

        .right-icons ul li {
            margin-left: 25px;
        }

        .right-icons ul li a {
            color: #a11515;
            font-size: 18px;
            text-decoration: none;
        }
        .description {
            display: -webkit-box; /* Needed for WebKit-based browsers */
            -webkit-box-orient: vertical; /* Vertical text layout */
            overflow: hidden; /* Hide overflowing content */
            text-overflow: ellipsis; /* Add ellipsis at the end of truncated text */
            -webkit-line-clamp: 3; /* Limit to 3 lines */
            line-height: 1.5; /* Adjust line height */
            max-height: calc(1.5em * 3); /* Calculate max height based on line height */
        }
        .meeting-item {
            width: 100%; /* Ensures it fits within the grid column */
            max-width: 350px; /* Optional: Set a maximum width for larger screens */
            height: 380px; /* Fixed height to ensure uniformity */
            display: flex;
            flex-direction: column;
            border: 1px solid #ddd; /* Optional: Add a border for better definition */
            border-radius:24px; /* Rounded corners */
            overflow: hidden; /* Ensures no overflowing content */
            margin: 10px auto; /* Center the cards and add some spacing */
            background-color: #fff; /* Ensure a consistent background color */
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Subtle shadow for a professional look */
        }

        .meeting-item .thumb img {
            width: 100%; /* Ensures the image fits the card width */
            height: 200px; /* Fixed height for images */
            object-fit: cover; /* Ensures the image scales correctly */
            border-bottom: 1px solid #ddd; /* Optional: Add a separator below the image */
        }



        .down-content .date {
            margin-bottom: 10px; /* Space between date and other content */
        }

        .down-content h4 {
            font-size: 18px; /* Adjust heading size */
            margin-bottom: 10px;
        }

        .down-content p {
            font-size: 14px; /* Adjust text size */
            color: #666; /* Subtle text color */
        }
        .modal-content {
            border-radius: 12px;
            overflow: hidden;
            background-color: #f9f9f9;
        }

        .modal-header {
            border-bottom: none;
            padding: 15px 20px;
        }

        .modal-header h5 {
            font-size: 1.5rem;
            margin: 0;
        }

        .modal-body {
            padding: 20px 30px;
            font-size: 0.95rem;
        }

        .modal-body p {
            font-size: 0.9rem;
            line-height: 1.5;
            color: #6c757d;
        }

        .modal-body .form-control {
            border-radius: 6px;
            border: 1px solid #ddd;
            padding: 10px;
            font-size: 0.9rem;
        }

        .modal-body .form-control:focus {
            border-color: #a11515;
            box-shadow: 0 0 5px rgb(161, 21, 21);
        }

        .modal-footer {
            border-top: none;
            padding: 15px 20px;
        }

        .btn-success {
            background-color: #a11515;
            border-color: #a11515;
            transition: background-color 0.3s ease;
        }

        .btn-success:hover {
            background-color: #a11515;
            border-color: #a11515;
        }

        .btn-secondary {
            background-color: #6c757d;
            border-color: #6c757d;
            transition: background-color 0.3s ease;
        }

        .btn-secondary:hover {
            background-color: #5a6268;
            border-color: #545b62;
        }
        .bg-primary {
            background-color: #a11515 !important;
        }
    </style>


{% endblock %}